### ISSUE TITLE
[MRESOURCES-2] "No such file or directory" when resource targetdirectory contains "../" and target/classes does not exist.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#120]
**[Mark Donszelmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=duns)** opened **[MRESOURCES-2](https://issues.apache.org/jira/browse/MRESOURCES-2?redirect=false)** and commented

"No such file or directory" when resource targetdirectory contains "../" and target/classes does not exist.

example:

    <resource>
        <targetPath>../generated-sources/filter</targetPath>
        <filtering>true</filtering>
        <directory>${basedir}/src/main/java</directory>
        <includes>
            <include>**/*</include>
        </includes>
    </resource>

since the targetdirectory is relative to "target/classes" (or whatever the setting is to put the class files)
the plugin fails with a

"No such file or directory: ....target/classes/../generated-sources/filter/....."

if target/classes does not exist.

On Windows it works fine, on Unix it fails.

Workaround: copy some resources to target/classes first, so that target/classes exists.

---

**Attachments:**
- [MNG-1345-maven-resources-plugin.patch](https://issues.apache.org/jira/secure/attachment/12718350/MNG-1345-maven-resources-plugin.patch) (_805 bytes_)

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

Hi, what version are you using?

I can't seem to reproduce this bug using your submitted configuration.

Also, since it works on Windows, could the problem be regarding your write permissions on Unix ?

I did check the code and found that mkdirs() is not being check if it returned true/false, but that's another issue.  ^_^

**Comment by jira-importer** [comment]
**[Mark Donszelmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=duns)** commented

Maven 2.0
maven-resources-plugin 2.1

checked on unix:

one cannot do:

ls non-existing-directory/../existing-directory

or even

mkdir non-existing-directory/../new-directory

though

mkdir -p non-existing-directory/../new-directory works.

below the real output:

---

[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error copying resources

Embedded error: /afs/slac.stanford.edu/u/ec/duns/w8/freehep-m2/freehep-tools/freehep-aid/target/classes/../generated-sources/filte$
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error copying resources
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:544)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error copying resources
at org.apache.maven.plugin.resources.ResourcesMojo.copyResources(ResourcesMojo.java:176)
at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:100)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more
Caused by: java.io.FileNotFoundException: /afs/slac.stanford.edu/u/ec/duns/w8/freehep-m2/freehep-tools/freehep-aid/target/classes/$
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.\<init>(FileOutputStream.java:179)
at java.io.FileOutputStream.\<init>(FileOutputStream.java:131)
at java.io.FileWriter.\<init>(FileWriter.java:73)
at org.apache.maven.plugin.resources.ResourcesMojo.copyFile(ResourcesMojo.java:228)
at org.apache.maven.plugin.resources.ResourcesMojo.copyResources(ResourcesMojo.java:172)
... 19 more
[INFO] ----------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Mark Donszelmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=duns)** commented

Unix/AFS permissions are ok.

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

In that case, you can omit the "./" and just use generated-sources/filter.

Can you try it?

**Comment by jira-importer** [comment]
**[Mark Donszelmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=duns)** commented

its "../" and not "./"

if I remove it, the filtered sources end up in "target/classes/generated-sources/filter" rather than "target/generated-sources/filter"

The whole problem is that targetPath is relative to "target/classes" rather than "target", which is why I put "../"

I guess the maven-resources-plugin should just create "target/classes" by default.

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

I get it !!!

Sorry about that.   My monitor resolution is at 1920 x 1200 in a 15" monitor so i really couldn't tell.

I'll have a fix for it in a while...

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

Attached is the patch to fix this.

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

- you could change the comment to something like "make sure the output directory exists". More generic
- you could print a warning if mkdirs() failed. As you are within the if (! exists()) mkdirs won't be called when the file already exist, and you won't get false positive warnings.
- I guess the issue already happens if the target is an absolute path pointing to a non existing directory. Would you mind testing?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Applied Edwin's patch, with a minor change:

I followed Jerome's suggestion and coded it to throw an exception when outputDir.mkdirs() returns false. The message will include the file path it tried to create.

Thanks for the patch, Edwin!
