### ISSUE TITLE
[MRESOURCES-1] Adding resources section to POM without directory element causes NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#124]
**[David Jackman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djackman)** opened **[MRESOURCES-1](https://issues.apache.org/jira/browse/MRESOURCES-1?redirect=false)** and commented

Add a resources section to a POM without a directory element (in my case I did have a filtering element, but that doesn't seem to matter).  Do a build (at least to the resources:resources goal).  A NullPointerException is thrown:
java.lang.NullPointerException
at java.io.File.\<init>(File.java:180)
at org.apache.maven.plugin.resources.ResourcesMojo.copyResources(ResourcesMojo.java:104)
at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:90)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:554)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:508)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:494)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:307)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:217)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Obviously, this is an error situation, but instead of throwing a runtime exception, the resources plugin should report an error that a directory was not provided.

---
No further details from [MRESOURCES-1](https://issues.apache.org/jira/browse/MRESOURCES-1?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

added to pom validation
