### ISSUE TITLE
[MRESOURCES-19] classcastexception when filtering a test resource with a ${basedir} defined

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#135]
**[Lars Rosenberg Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larsrnielsen)** opened **[MRESOURCES-19](https://issues.apache.org/jira/browse/MRESOURCES-19?redirect=false)** and commented

I got a classcastexception when trying to filter a test resource with a ${basedir} defined.

mvn -e test

[INFO] Trace
java.lang.ClassCastException: java.io.File
at org.codehaus.plexus.util.InterpolationFilterReader.read(Interpolation
FilterReader.java:269)
at org.codehaus.plexus.util.InterpolationFilterReader.read(Interpolation
FilterReader.java:162)
at java.io.Reader.read(Reader.java:100)
at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:212)
at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:200)
at org.apache.maven.plugin.resources.ResourcesMojo.copyFile(ResourcesMoj
o.java:249)
at org.apache.maven.plugin.resources.ResourcesMojo.copyResources(Resourc
esMojo.java:172)
at org.apache.maven.plugin.resources.TestResourcesMojo.execute(TestResou
rcesMojo.java:53)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] ---------------------------------------------------------------------

---

**Issue Links:**
- [MRESOURCES-10](https://issues.apache.org/jira/browse/MRESOURCES-10) Filtering should handle java.io.File values
 (_**"duplicates"**_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Lars Rosenberg Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larsrnielsen)** commented

it is actually more general than reported. If I reference ${basedir} or ${pom.basedir} in a filtered resource or in the filter properties file then I get the classcastexception as described.
