### ISSUE TITLE
[MRESOURCES-61] PluginDescriptor not found

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#179]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** opened **[MRESOURCES-61](https://issues.apache.org/jira/browse/MRESOURCES-61?redirect=false)** and commented

The following error, every time I run a build has been ongoing for quite some time now.

3/21/08 3:34:06 PM EDT: Build error for /aleixo-console/pom.xml; java.lang.IllegalStateException: The PluginDescriptor for the plugin org.apache.maven.plugins:maven-resources-plugin was not found

It seems to go away if I run with a -U to update the plugins but comes back regularly.

Can somebody please fix whatever issue is causing this to occur?

---

**Attachments:**
- [maven-eclipse-integration-plugin.txt](https://issues.apache.org/jira/secure/attachment/12718376/maven-eclipse-integration-plugin.txt) (_19.96 kB_)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Please provide a complete build log with stacktrace turned on.

mvn package -e

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

Of course I can't get it to happen now... I'll post a stack trace when I next encounter it, but its been happening for about 4-6 months now.

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

Ok, got the stack trace. This is the same exception I've been getting for month on various machines including Mac, Linux and Windows of various versions. It seem to only be after a day has gone by and maven thinks it needs to update the plugin.

Now, in this particular case (which is not always the case) the artifact is being downloaded from an Archiva repository... however if it was unable to check for a new version of the plugin, I should at **most** be getting a warning only, my build that worked yesterday should not be failing today just because it couldn't check for an update to a plugin (in this case it's actually Archiva that's getting the error and passing it back).

Also, it's **ALWAYS** the resources plugin... any other plugin and I know I may have a configuration issue, but this particular problem seems to be limited to the resources plugin consistently.

== Full output follow ==

$ mvn -U -e deploy
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] snapshot com.empirical:empirical:1.0.0-SNAPSHOT: checking for updates from internal
  [WARNING] repository metadata for: 'snapshot com.empirical:empirical:1.0.0-SNAPSHOT' could not be retrieved from repository: internal due to an error: GET request of: com/empirical/empirical/1.0.0-SNAPSHOT/maven-metadata.xml from internal failed
  [INFO] Repository 'internal' will be blacklisted
  WAGON_VERSION: 1.0-beta-1
  [INFO] ------------------------------------------------------------------------
  [INFO] Building NetSuite Web Services
  [INFO]    task-segment: [deploy]
  [INFO] ------------------------------------------------------------------------
  [INFO] artifact org.apache.maven.plugins:maven-resources-plugin: checking for updates from central
  [WARNING] repository metadata for: 'artifact org.apache.maven.plugins:maven-resources-plugin' could not be retrieved from repository: central due to an error: GET request of: org/apache/maven/plugins/maven-resources-plugin/maven-metadata.xml from internal-central failed
  [INFO] Repository 'central' will be blacklisted
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
  [INFO] ------------------------------------------------------------------------
  [INFO] Trace
  org.apache.maven.lifecycle.LifecycleExecutionException: The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1286)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1522)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindLifecycleForPackaging(DefaultLifecycleExecutor.java:1016)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:980)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
  Caused by: org.apache.maven.plugin.version.PluginVersionNotFoundException: The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
  at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.java:229)
  at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.java:91)
  at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:167)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1257)
  ... 18 more
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: 2 seconds
  [INFO] Finished at: Tue Mar 25 13:23:39 EDT 2008
  [INFO] Final Memory: 1M/4M
  [INFO] ------------------------------------------------------------------------
  [brillp@build empirical-netsuite]$

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Have a look at the stack trace.
It says "Repository 'central' will be blacklisted"  (and Repository 'internal' will be blacklisted).
This means you don't have internet access !

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

Yes, in that case I needed a VPN up... however my build should still not fail.
The fact is that the plugin is already in my local repo... verified and checked.

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

This evening I have another one for you. different machine, different OS, different network etc but the same problem.
This one is from the Maven Eclipse Integration plugin, with debug turned on. I'm including all the output int he hope that it will give you guys a clue however the relevant portion is:

---

3/25/08 8:49:19 PM EDT: [DEBUG] Using the following artifacts for classpath of: org.apache.maven.plugins:maven-resources-plugin:maven-plugin:2.3-SNAPSHOT:

[org.codehaus.plexus:plexus-utils:jar:1.1:runtime]
3/25/08 8:49:19 PM EDT: [DEBUG] Retrieving realm for plugin with id: /plugins/org.apache.maven.plugins:maven-resources-plugin:2.3-20060725.131549-1@48
3/25/08 8:49:19 PM EDT: [DEBUG] Creating realm for plugin with id: /plugins/org.apache.maven.plugins:maven-resources-plugin:2.3-20060725.131549-1@48
3/25/08 8:49:19 PM EDT: [DEBUG] Created realm: ClassRealm[/plugins/org.apache.maven.plugins:maven-resources-plugin:2.3-20060725.131549-1@48, parent: null] for plugin: org.apache.maven.plugins:maven-resources-plugin
3/25/08 8:49:19 PM EDT: [DEBUG] Discovering components in realm: ClassRealm[/plugins/org.apache.maven.plugins:maven-resources-plugin:2.3-20060725.131549-1@48, parent: null]
3/25/08 8:49:19 PM EDT: [DEBUG] Checking for plugin descriptor for: org.apache.maven.plugins:maven-resources-plugin with version: 2.3-20060725.131549-1 in collector: org.apache.maven.plugin.MavenPluginCollector@603c9f
3/25/08 8:49:19 PM EDT: Build error for /sgutility/pom.xml; java.lang.IllegalStateException: The PluginDescriptor for the plugin org.apache.maven.plugins:maven-resources-plugin was not found

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

lock plugin versions in your pom !

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

Yes I can do that, but I shouldn't have to... every other plugin works just fine.
The point of **not** locking it is that you get updates (like when this issue gets some respect)  :)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> The point of not locking it is that you get updates
> If you ever cared about reproducible builds, then I can only emphasize to follow Oliver's suggestion and lock plugin versions. While auto-update originally seemed like a convenient feature, it makes your build dependent on current time and machine/developer. The key point to keep in mind is that a new plugin version simply might not be backwards compatible, may it for a new bug or some refactoring to better support new/other use cases.

Last but not least, be warned that Maven 2.0.9 will lock down core plugins in its super POM, see MNG-3395.

**Comment by jira-importer** [comment]
**[Brill Pappin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brill)** commented

I'm not saying its a bad idea (in fact I think it might be a good one). however its more complicated than that... for instance I **do** want reproducible builds, however the plugin should fix problems it has... otherwise the build is only as reproducible as the bug I worked around.
Reproducible means to me that my code compiles, tests and packages as expected the same way, every time, not that the resources plugin uses a different route to do what it needs to do (if thats the case, I've written some very poor code indeed).
Maybe the answer is to have maven warn when it detects an update and give you the option of installing... I don't know... however thats not the issues here, this is not MNG-3395.

As for Maven locking down versions, it should have at least shipped with released versions of plugins... which apparently the resources plugin was not.

What I am saying:
a) i shouldn't have to worry about the resources plugin failing my build or not.
b) even if I don't specifically lock down, i still shouldn't get the error I have been getting.
c) all other plugins work without all that noise, including third party plugins (and my own plugins).

I can't tell from my perspective if its an issue with maven dependency system or the resources plugin descriptor (which is what the error is) however, regardless of how I use it, there is still something that the developers of the resources plugin need to address.
