### ISSUE TITLE
[MRESOURCES-49] Maven 2 resources:resources causes NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#206]
**[Martin Gainty](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgainty@hotmail.com)** opened **[MRESOURCES-49](https://issues.apache.org/jira/browse/MRESOURCES-49?redirect=false)** and commented

Download Jetty 6.1.0
cd /Jetty/jetty-6.1.0
mvn
everything is fine until the resources plugin is called and then NPE

[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[GC [DefNew: 3962K->0K(4032K), 0.0059200 secs] 47622K->44219K(262080K), 0.006027
0 secs]
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] null
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.PathUtils.protocol(PathUtils.java:206)
at org.apache.maven.wagon.repository.Repository.setUrl(Repository.java:1
19)
at org.apache.maven.wagon.repository.Repository.\<init>(Repository.java:7
2)
at org.apache.maven.artifact.repository.DefaultArtifactRepository.\<init>
(DefaultArtifactRepository.java:67)
at org.apache.maven.artifact.repository.DefaultArtifactRepositoryFactory
.createDeploymentArtifactRepository(DefaultArtifactRepositoryFactory.java:41)
at org.apache.maven.project.ProjectUtils.buildDeploymentArtifactReposito
ry(ProjectUtils.java:77)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLog
ic(DefaultMavenProjectBuilder.java:751)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:631)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromReposito
ry(DefaultMavenProjectBuilder.java:353)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenM
etadataSource.java:102)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(D
efaultArtifactCollector.java:282)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(D
efaultArtifactCollector.java:67)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:223)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:211)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTra
nsitively(DefaultArtifactResolver.java:182)
at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsC
omplete(DefaultPluginManager.java:611)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(Defaul
tPluginManager.java:522)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:393)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: 13 seconds

This is a blocker since I cant build jetty 6.1.0

---
No further details from [MRESOURCES-49](https://issues.apache.org/jira/browse/MRESOURCES-49?redirect=false)

**Comment by jira-importer** [comment]
**[Martin Gainty](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgainty@hotmail.com)** commented

maven 2.0.7 fixes the resources:resources NPE and produces \jetty-6.1.0\modules\util\target\jetty-util.jar

**Comment by jira-importer** [comment]
**[Paul Gier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pgier)** commented

Martin, can this issue be closed?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I cannot reproduce.
If you can, please reopen the issue with a simple project which reproduce the issue.
Thanks.
