### ISSUE TITLE
[MRESOURCES-125] Error during escaping

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#259]
**[Fabrice Scoyer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fabrice)** opened **[MRESOURCES-125](https://issues.apache.org/jira/browse/MRESOURCES-125?redirect=false)** and commented

If I have \${user.dir} in my filtered file I obtain the error bellow. It works with 2.3 release, not latest

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources (default-resources) on project pec-web: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources failed. StringIndexOutOfBoundsException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources (default-resources) on project pec-web: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources failed.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:578)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:247)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:104)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:423)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:158)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
at java.lang.reflect.Method.invoke(Method.java:600)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources failed.
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:114)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:562)
... 14 more
Caused by: java.lang.StringIndexOutOfBoundsException
at java.lang.StringBuffer.replace(StringBuffer.java:614)
at org.codehaus.plexus.interpolation.multi.MultiDelimiterStringSearchInterpolator.interpolate(MultiDelimiterStringSearchInterpolator.java:212)
at org.codehaus.plexus.interpolation.multi.MultiDelimiterStringSearchInterpolator.interpolate(MultiDelimiterStringSearchInterpolator.java:150)
at org.codehaus.plexus.interpolation.multi.MultiDelimiterInterpolatorFilterReader.read(MultiDelimiterInterpolatorFilterReader.java:427)
at org.codehaus.plexus.interpolation.multi.MultiDelimiterInterpolatorFilterReader.read(MultiDelimiterInterpolatorFilterReader.java:231)
at java.io.Reader.read(Reader.java:135)
at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:212)
at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:200)
at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2222)
at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2170)
at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:115)
at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:262)
at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:263)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
... 15 more

---

**Affects:** 2.4, 2.4.1, 2.4.2, 2.4.3

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Which version of Maven are you using?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This seems to work for me.
Can you put together a sample project and tell us the expected and actual results.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

No reponse from reporter.
