### ISSUE TITLE
[MRESOURCES-176] CNFE for MavenFilterException 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#361]
**[Monish Sen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mastermind3043)** opened **[MRESOURCES-176](https://issues.apache.org/jira/browse/MRESOURCES-176?redirect=false)** and commented

While executing goal install with default profile maven resource plugin version(2.4.1) throws below exception

```
[INFO] ------------------------------------------------------------------------
[INFO] Building ---Services 1.0-A-SNAPSHOTS
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.4.1:resources (default-resources) @ ---ServicesWeb ---
Nov 29, 2013 3:06:44 PM org.sonatype.guice.bean.reflect.LoadedClass
WARNING: Error injecting: org.apache.maven.plugin.resources.ResourcesMojo
java.lang.NoClassDefFoundError: org/apache/maven/shared/filtering/MavenFilteringException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2437)
	at java.lang.Class.getDeclaredConstructors(Class.java:1863)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:628)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:835)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:769)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:254)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:843)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:957)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:951)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1003)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:47)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:968)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1014)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:964)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:79)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:53)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:235)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.shared.filtering.MavenFilteringException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 47 more
```

M2E plugin in Eclipse shows below error

```
Multiple annotations found at this line:
	- Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources failed: A required class was missing while executing 
	 org.apache.maven.plugins:maven-resources-plugin:2.4.1:resources: org/apache/maven/shared/filtering/MavenFilteringException 
	 ----------------------------------------------------- realm = plugin>org.apache.maven.plugins:maven-resources-plugin:2.4.1 strategy = 
	 org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy urls[0] = file:/Users/monish/mvnrepo/org/apache/maven/plugins/maven-resources-plugin/2.4.1/maven-
	 resources-plugin-2.4.1.jar urls[1] = file:/Users/monish/mvnrepo/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar Number of foreign imports: 1 import: 
	 Entry[import from realm ClassRealm[maven.api, parent: null]] ----------------------------------------------------- (org.apache.maven.plugins:maven-
	 resources-plugin:2.4.1:resources:default-resources:process-resources)
	- Execution default-testResources of goal org.apache.maven.plugins:maven-resources-plugin:2.4.1:testResources failed: A required class was missing while 
	 executing org.apache.maven.plugins:maven-resources-plugin:2.4.1:testResources: org/apache/maven/shared/filtering/MavenFilteringException 
	 ----------------------------------------------------- realm = plugin>org.apache.maven.plugins:maven-resources-plugin:2.4.1 strategy = 
	 org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy urls[0] = file:/Users/monish/mvnrepo/org/apache/maven/plugins/maven-resources-plugin/2.4.1/maven-
	 resources-plugin-2.4.1.jar urls[1] = file:/Users/monish/mvnrepo/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar Number of foreign imports: 1 import: 
	 Entry[import from realm ClassRealm[maven.api, parent: null]] ----------------------------------------------------- (org.apache.maven.plugins:maven-
	 resources-plugin:2.4.1:testResources:default-testResources:process-test-resources)

```

Issue is not faced with version 2.5 and 2.6

---

**Affects:** 2.4.1, 2.6

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Did you try clearing your local repository ?

**Comment by jira-importer** [comment]
**[Monish Sen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mastermind3043)** commented

Hi Kristian,

Thanks for your response.

I've tried cleaning. The issue is not with a corrupted jar. Also tried maunally installing the 2.4.1 jar from central.

**Comment by jira-importer** [comment]
**[Andrey Sharko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kimrli)** commented

Hi there, first error from description has been found using Maven 3.1.1 and maven-resource-plugin 2.6

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi, can you please describe more in detail how you called the resources plugin and how you started maven etc. May be you can offer a logoutput file for a more detailed analysis?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Based on the comments there is no issue with 2.5 and 2.6 so i close the issue cause in the meantime we have 2.7 out. If you have further information like an example project which reproduces the behaviour don't hesitate to reopen the issue.
