### ISSUE TITLE
[MRESOURCES-186] Improve error handling based on Mark invalid

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-resources-plugin#365]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** opened **[MRESOURCES-186](https://issues.apache.org/jira/browse/MRESOURCES-186?redirect=false)** and commented

Sometimes it can happen that filtering is done on files which shouldn't be filtered...which results in the following:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.7:resources (default-resources) on project OrionCommunity: Mark invalid -> [Hel
p 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.7:resources (default-resources)
 on project OrionCommunity: Mark invalid
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Mark invalid
        at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:306)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Mark invalid
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:129)
        at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:264)
        at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:300)
        ... 21 more
Caused by: java.io.IOException: Mark invalid
        at java.io.BufferedReader.reset(BufferedReader.java:485)
        at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:416)
        at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:205)
        at java.io.Reader.read(Reader.java:123)
        at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:181)
        at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:168)
        at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1856)
        at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1804)
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:114)
```

Currently this only crashes the build. But it might be better to create an appropriate error message for the user.

---

**Affects:** 2.7

**Issue Links:**
- [MRESOURCES-189](https://issues.apache.org/jira/browse/MRESOURCES-189) [Regression] Resource filtering fails when encounters binary files

- [MWAR-331](https://issues.apache.org/jira/browse/MWAR-331) IOException: Mark invalid -- With version 2.5

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

I ran into this issue after upgrade from 2.6 to 2.7, my build fails b/c my resources directory has binary files.  This is a regression, isn't it? and critical as well since now I can't upgrade unless i have do specific file filtering. The resource-able files are scatter in my resources directory and it is tough to maintain.

Can we find out why the feature got removed( ie able to detect binary file an skip filtering?)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

Detecting whether a file is binary or text is not trivial, not sure how m-r-p 2.6 did, perhaps ignore the exception?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hm...as i wrote on the [users list i can reproduce this issue](http://maven.40175.n5.nabble.com/Problem-with-the-resource-plugin-v2-7-and-nonFilteredFileExtensions-tc5807863.html) by filtering an artifact which shouldn't be filtered. I have tested this with the integration tests of this plugin `maven-resources-plugin/src/it/binaries-filtering` which gives me the impression that it is not a regression. Can you check your build doing `mvn -X generate-resources` and look into the output of the log file for output like `filtering` and which files are being filtered....

like the following:

```
[DEBUG] file duke-beerjpg.img has a filtered file extension
[DEBUG] filtering /maven-resources-plugin/target/it/possible-bug/src/main/resources/duke-beerjpg.img
to /maven-plugins/maven-resources-plugin/target/it/possible-bug/target/classes/duke-beerjpg.img
```

In the above it shows that the `.img` files will be filtered which is not correct cause they contain bytes which are interpreted as markers for encoding etc. In this case i have a file duke-beerjpg.img which is filtered but should not being filter which is causing the failure...

I have added an example project https://github.com/khmarbaise/mresources/tree/master/mresources-186 where you can see the results and we can do further discussion to that.

If you run the project as given via `mvn clean process-resources` with the configured version of maven-resources-plugin (2.6) you will get an sucessfull build. But if you take a look into the target folder and compare the created files:

First original location:

```
Karl-Heinzs-MacBook-Pro:mresources-186 kama$ ls -al src/main/resources/
total 1552
drwxr-xr-x  5 kama  staff     170 Oct 11 19:37 .
drwxr-xr-x  3 kama  staff     102 Oct 11 19:37 ..
-rw-r--r--  1 kama  staff  749914 Oct 11 19:37 duke-beerjpg.img
-rw-r--r--  1 kama  staff     808 Oct 11 19:37 file.txt
-rw-r--r--  1 kama  staff   36092 Oct 11 19:37 happy_duke.gif
```

Now target/classes folder:

```
Karl-Heinzs-MacBook-Pro:mresources-186 kama$ ls -al target/classes/
total 2664
drwxr-xr-x  5 kama  staff      170 Oct 11 19:39 .
drwxr-xr-x  3 kama  staff      102 Oct 11 19:39 ..
-rw-r--r--  1 kama  staff  1321860 Oct 11 19:39 duke-beerjpg.img
-rw-r--r--  1 kama  staff      806 Oct 11 19:39 file.txt
-rw-r--r--  1 kama  staff    36092 Oct 11 19:39 happy_duke.gif
Karl-Heinzs-MacBook-Pro:mresources-186 kama$
```

This shows the size of the `.img` has changed which is simply wrong! If i try to use resources-plugin 2.7 which result in a failure which gives me a hint that this files should be configured not being filtered via:
{```xml
\<configuration>
\<nonFilteredFileExtensions>
\<nonFilteredFileExtension>img\</nonFilteredFileExtension>
\</nonFilteredFileExtensions>
\</configuration>

```
This results in a sucessfull build and the size of the .img files is the same as expected.
```

[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ maven-resources-plugin-binaries-filtering ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.928s
[INFO] Finished at: Sat Oct 11 19:45:24 CEST 2014
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------
Karl-Heinzs-MacBook-Pro:mresources-186 kama$ ls -al src/main/resources/
total 1552
drwxr-xr-x  5 kama  staff     170 Oct 11 19:37 .
drwxr-xr-x  3 kama  staff     102 Oct 11 19:37 ..
-rw-r--r--  1 kama  staff  749914 Oct 11 19:37 duke-beerjpg.img
-rw-r--r--  1 kama  staff     808 Oct 11 19:37 file.txt
-rw-r--r--  1 kama  staff   36092 Oct 11 19:37 happy_duke.gif
Karl-Heinzs-MacBook-Pro:mresources-186 kama$ ls -al target/classes/
total 1552
drwxr-xr-x  5 kama  staff     170 Oct 11 19:45 .
drwxr-xr-x  3 kama  staff     102 Oct 11 19:45 ..
-rw-r--r--  1 kama  staff  749914 Oct 11 19:45 duke-beerjpg.img
-rw-r--r--  1 kama  staff     806 Oct 11 19:45 file.txt
-rw-r--r--  1 kama  staff   36092 Oct 11 19:45 happy_duke.gif

```
May be you can add some of your examples as pull request to the example project so we check if it is a regression or not?
```

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

I am lowering the severity since it has a work around

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

From my point of view m-r-p:2.7 shows better that something is wrong in your build than 2.6 did (just ignores without any hint). So from this point i don't see it as a regression nor as a bug.  Apart from that it's not a work around it brings your build where it should be which means to define those extensions which should not been filtered which was wrong before.

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

I agree it is wrong trying to filter files that are not intended to do. I guess it is an accidental good regression. and should be doc.  A  error message showing the file path is very helpfull

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

So this is not a failure of filtering it is as originally an improvement of error output...Can you change to the original headline back. If we had reall  regression than you should create a separate issue for that instead of changing an existing one.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Probably exposed due to MSHARED-199. With this issue, if the start-delimiter is found but not the end-delimiter, it will continue after the start-delimiter without filtering. However, there is a maximum amount of bytes which can be read after the marked position of the start-delimiter.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Fixed by MRESOURCES-192
